# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  MylocalPool

steps:
  - script: npm install
    displayName: 'Run a one-line script'
    
  - task: configuration@1
    inputs:
        connection: 'sunil-test'
        isTunnelActivate: false
        isAppAutomate: false
        isSmartUI: false

  - script: |
      npm run SingleAndroidWeb  
      displayName: 'Run a multi-line script'
      
  - task: LambdatestResults@1

      
# - stage: LambdatestResults
#   jobs:
#   - job: LambdatestResultsJob
#     steps:
#       - script: |
#           echo "Hello"