on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    env:
      LT_USERNAME: "sunilr"  # Set your desired environment variable here
      LT_ACCESS_KEY: "LtQPqIWXiN4kHjRSQ9juzDmQZV7tpbssbvyEJ13JPS4QfhGduU"
      LT_BUILD_NAME: "Github RUN ID-${{ github.run_id }}"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Display run_id
      run: echo "The GitHub run ID is $GITHUB_RUN_ID"

  

    - run: |
          npm i
          npm install
          npm i wdio-lambdatest-service --save-dev
          npm run SingleAndroidWeb
